apiVersion: v1
kind: Service
metadata:
  name: quant-frontend-lb
  namespace: tdsequential
  annotations:
    # OCI Load Balancer — Flexible shape, 10 Mbps (Free Tier eligible)
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  type: LoadBalancer
  selector:
    app: quant-frontend        # ชี้ไปที่ Frontend Pod
  ports:
    - name: http
      protocol: TCP
      port: 80                 # External Port (Public IP:80)
      targetPort: 80           # Frontend Container Port
